SELECT * FROM EMP;
-- 1.
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;
-- 2.
SELECT *
FROM EMP
WHERE COMM = 0 OR COMM IS NULL;
-- 3.
SELECT *
FROM EMP
WHERE MGR IS NULL;
-- 4.
SELECT *
FROM EMP
ORDER BY SAL DESC;
-- 5.
SELECT *
FROM EMP
ORDER BY COMM DESC, SAL DESC;

-- 6.
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM EMP
ORDER BY HIREDATE ASC; 
-- 7.
SELECT EMPNO, ENAME
FROM EMP
ORDER BY EMPNO DESC;
-- 8.
SELECT EMPNO, HIREDATE, ENAME, SAL
FROM EMP
ORDER BY DEPTNO ASC , HIREDATE DESC;
-- 9.
SELECT SYSDATE
FROM DUAL;
-- 10.
SELECT EMPNO ,ENAME , TRUNC(SAL, 2) 
FROM EMP
ORDER BY SAL DESC
;
-- 11.
SELECT *
FROM EMP 
WHERE MOD(EMPNO, 2) = 1;
-- 12.
SELECT ENAME, EXTRACT(YEAR FROM HIREDATE), EXTRACT(MONTH FROM HIREDATE)
FROM EMP
;
-- 13.
SELECT *
FROM EMP
WHERE EXTRACT(MONTH FROM HIREDATE) = 9
;
-- 14.
SELECT * 
FROM EMP
WHERE EXTRACT(YEAR FROM HIREDATE) = 1981
;
-- 15.
SELECT *
FROM EMP
WHERE ENAME LIKE '%E';
-- 16.
SELECT *
FROM EMP
WHERE ENAME LIKE '__R%';
-- 17. 못함
SELECT EMPNO , ENAME ,TO_CHAR(HIREDATE,'YY-MM-DD'),TO_CHAR(ADD_MONTHS(HIREDATE,480),'YY-MM-DD') 
FROM EMP
;
-- 18.
SELECT * 
FROM EMP
WHERE 2023 - EXTRACT (YEAR FROM HIREDATE)> 38
;
-- 19.
SELECT EXTRACT (YEAR FROM SYSDATE)
FROM DUAL
;