SELECT *
FROM EMPLOYEE e 
;
-- 1.
SELECT * 
FROM JOB
;
-- 2.
SELECT JOB_NAME
FROM JOB
;
-- 3.
SELECT *
FROM DEPARTMENT
;
-- 4.
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE
;
-- 5.
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE
;
-- 6.
SELECT EMP_NAME, SALARY, BONUS, (SALARY * 12 +	SALARY * NVL(BONUS,0) * 12 - (SALARY * 12 * 0.03)) "총수령액"
FROM EMPLOYEE
;
-- 7.
SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM EMPLOYEE 
WHERE SAL_LEVEL = 'S1'
;
-- 8.
SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM EMPLOYEE 
WHERE SALARY >4999999
;
-- 9.
SELECT *
FROM EMPLOYEE
WHERE (SALARY * 12 + SALARY * NVL(BONUS,0) * 12 - (SALARY * 12 * 0.03)) > 50000000
;
-- 9.
SELECT *
FROM EMPLOYEE
WHERE SALARY > 3999999 AND JOB_CODE = 'J2'
;
-- 10.
SELECT * 
FROM EMPLOYEE 
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D5') AND HIRE_DATE > TO_DATE('20020101','YYYY-MM-DD')
;
-- 11.
SELECT *
FROM EMPLOYEE 
WHERE (HIRE_DATE > TO_DATE('19900101','YYYY-MM-DD') AND HIRE_DATE < TO_DATE('20001201','YYYY-MM-DD')) AND SALARY > 2699999
;
-- 12.
SELECT *
FROM EMPLOYEE e
WHERE HIRE_DATE > '19900101' AND HIRE_DATE < '20010101'
;
-- 13.
SELECT *
FROM EMPLOYEE e
WHERE EMP_NAME LIKE '%연'
;
-- 14.
SELECT
	*
FROM
	EMPLOYEE e
WHERE
	EMAIL LIKE '____@_%' ESCAPE '@'
	AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6')
	AND (HIRE_DATE > '900101' AND HIRE_DATE < '001201')
	AND SALARY > 2699999
;
-- 15.
SELECT EMP_NAME , SUBSTR(EXTRACT (YEAR FROM HIRE_DATE) , 3, 2) 생년, EXTRACT (MONTH FROM HIRE_DATE) 월, EXTRACT (DAY FROM HIRE_DATE) 일
FROM EMPLOYEE e 
;
-- 16.
SELECT EMP_NAME , RPAD(SUBSTR(EMP_NO, 1,7),14,'*') AS "주민번호"
FROM EMPLOYEE e 
;
-- 17.
SELECT EMP_NAME , 
FROM EMPLOYEE e 
;
-- 18
SELECT *
FROM EMPLOYEE e 
WHERE MOD(EMP_ID, 2) = 1
;
-- 19.
SELECT *
FROM EMPLOYEE e 
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM HIRE_DATE) > 20
;
-- 20. EMPLOYEE 테이블에서 사원명, 급여 조회 (단, 급여는 '\9,000,000' 형식으로 표시)
SELECT EMP_NAME , LPAD(SALARY, 8 , '\') AS "급여 조회"
FROM EMPLOYEE e 
;
-- 20. EMPLOYEE테이블에서 직원 명, 부서코드, 생년월일, 나이(만) 조회
-- (단, 생년월일은 주민번호에서 추출해서 00년 00월 00일로 출력되게 하며
-- 나이는 주민번호에서 출력해서 날짜데이터로 변환한 다음 계산)
SELECT
	EMP_NAME ,
	DEPT_CODE ,
	SUBSTR(EMP_NO, 1, 2)||'년 '||SUBSTR(EMP_NO, 3, 2)||'월 '||SUBSTR(EMP_NO, 5, 2)||'일' AS "생년월일",
	EXTRACT(YEAR FROM sysdate) - (substr(EMP_NO, 1, 2) + 1900) AS "나이"
FROM
	EMPLOYEE e 
;
-- 22. EMPLOYEE테이블에서 부서코드가 D5, D6, D9인 사원만 조회하되 D5면 총무부, D6면 기획부, D9면 영업부로 처리
-- (단, 부서코드 오름차순으로 정렬)
SELECT EMP_ID  , EMP_NAME , DEPT_CODE, d.DEPT_TITLE 
FROM EMPLOYEE e 
	JOIN DEPARTMENT d ON e.DEPT_CODE = d.DEPT_ID
WHERE DEPT_CODE IN ('D5','D6','D9')
ORDER BY DEPT_CODE asc;

-- 23. EMPLOYEE테이블에서 사번이 201번인 사원명, 주민번호 앞자리, 주민번호 뒷자리,
-- 주민번호 앞자리와 뒷자리의 합 조회
SELECT
	EMP_NAME AS "사원명",
	substr(e.EMP_NO, 1, 6) AS "주민번호 앞자리",
	substr(e.EMP_NO, 8, 7) AS "주민번호 앞자리",
	substr(e.EMP_NO, 1, 6) + substr(e.EMP_NO, 8, 7) AS "주민번호 앞자리와 뒷자리의 합"
FROM
	EMPLOYEE e
WHERE
	EMP_ID IN ('201')
;
-- 24. EMPLOYEE테이블에서 부서코드가 D5인 직원의 보너스 포함 연봉 합 조회
SELECT
	sum((SALARY + (SALARY * nvl(BONUS, 0))) * 12) AS "부서 총수령액"
FROM 
	EMPLOYEE e
WHERE 
	DEPT_CODE IN 'D5'
;

-- 25. EMPLOYEE테이블에서 직원들의 입사일로부터 년도만 가지고 각 년도별 입사 인원수 조회
-- 전체 직원 수, 2001년, 2002년, 2003년, 2004년
SELECT
	count(EMP_ID),
	count(CASE when (EXTRACT(YEAR FROM HIRE_DATE)) = 2001 THEN 1 end) AS "2001년",
	count(CASE when (EXTRACT(YEAR FROM HIRE_DATE)) = 2002 THEN 1 end) AS "2001년",
	count(CASE when (EXTRACT(YEAR FROM HIRE_DATE)) = 2003 THEN 1 end) AS "2001년",
	count(CASE when (EXTRACT(YEAR FROM HIRE_DATE)) = 2004 THEN 1 end) AS "2001년"
FROM EMPLOYEE e
;
